codeit-sprint-4-project-1-team7/project-1-team7

src/index.css
=> test: 풀리퀘스트 테스트

public/index.html, src/component/common/header/HeaderService.jsx, src/component/common/header/KaKaoShare.jsx, src/component/pages/PostDetail.jsx
- headerService 적용 
- 공유하기 버튼 클릭 이벤트 추가
- 카카오톡 공유 기능 추가
=> post/{id} 페이지 기능 추가

src/util/api.js
=> API 파일 및 코드 작성

src/component/common/header/HeaderService.module.css, src/component/pages/PostDetail.jsx
=> 주석 추가 및 api 테스트 코드 작성

package-lock.json, package.json, src/component/common/header/HeaderService.jsx, src/component/common/header/HeaderService.module.css
이모지의 api를 프로젝트 clone 시 자동으로 받아질 수 있는 코드 추가.
=> 이모지 관련 코드 추가

src/component/common/button/Button.jsx
=> [윤아영] Button 컴포넌트

src/component/pages/Main.jsx, src/component/pages/Main.module.css
Main 페이지 디자인 적용 (반응형 웹 디자인 포함)
=> [홍성욱] Design: Main 페이지 디자인 적용 (반응형 포함)

src/component/common/header/Header.module.css
페이지 이동 시 header의 height값 변경되는 부분 관련 css 추가로 해결
=> Style: 페이지 이동 시 header의 height값 변경되는 부분 관련 css 추가로 해결

src/component/pages/PostDetailEdit.jsx, src/component/pages/PostDetailEdit.module.css
- 데이터를 받고 삭제하기 위해서 Swagger 문서에서 데이터들을 임시로 추가해봤는데 배이스 주소가 달라서 사용할 api 함수가 있습니다.
- Card 컴포넌트 데이터를 전달할 수가 없어서 임시로 복사 붙여넣기 했습니다.
- 전체적인 그리드를 간단하게 구현했습니다.
- 임시로 만든 api함수와 카드 컴포넌트는 이후 기존에 존재하는 것으로 바꿀 예정입니다.
=> [윤아영] post/edit 파일 내 카드 리스트 추가 및 카드 삭제 구현

src/component/pages/PostDetailEdit.jsx, src/component/pages/PostDetailEdit.module.css
- 삭제하기 버튼 클릭 시 해당 롤링페이퍼를 제거합니다. 롤링페이퍼를 제거한 이후 list 페이지로 이동합니다.
- 찾을 수 없는 id의 edit 페이지로 간다면 에러 메시지를 화면에 보여줍니다.
- messages가 없는 경우를 대비하여 옵셔널 체이닝을 사용하였습니다.
- 임시로 사용하던 api 함수를 기존에 존재하는 api 함수로 변경하였습니다.
=> [윤아영] 삭제하기 버튼 구현 및 예외 처리

src/component/common/card/Card.jsx, src/component/common/cardList/CardList.jsx, src/component/common/cardList/CardList.module.css, src/component/common/header/HeaderService.jsx, src/component/common/header/HeaderService.module.css, src/component/common/header/ProfileImages.jsx, src/component/pages/Post.jsx, src/component/pages/PostDetail.jsx, src/component/test/Kim.jsx
1. 테스트를 위한 코드 추가
2. api 연동을 위한 코드 추가, 연동 완료
3. 대문자 폴더명 I를 i로 변경하여 오류 제거
=> [김수환] 각종 api 연동

src/component/common/card/Card.jsx, src/component/common/card/Card.module.css, src/component/common/header/HeaderService.jsx, src/component/common/header/HeaderService.module.css, src/component/common/header/KaKaoShare.jsx, src/component/pages/Layout.jsx, src/component/pages/PostDetail.jsx, src/util/api.js, src/util/isImageValid.js
=> [김수환] postDetail 페이지 개발

src/component/pages/PostMessage.jsx
- postMessage 페이지 post 기능 테스트 완료
=> [최원석] Feat: postMessage 페이지 post 기능 테스트 완료

src/component/common/button/Button.jsx, src/component/common/button/Button.module.css, src/component/common/button/CircleButton.module.css, src/component/common/button/ToggleButton.module.css
- 미디어 쿼리를 적용하기 위해서 width를 인라인 스타일이 아닌 클래스 이름을 통해서 조정하도록 수정했다.
- 버튼에 마우스 모양이 pointer가 되도록 하고 disabled인 경우에는 not-allowed 되도록 한다.
=> [윤아영] Button 컴포넌트 수정

src/component/common/header/HeaderService.module.css
=> Style: 중앙정렬 css추가

src/component/pages/List.jsx, src/component/pages/List.module.css
[개선 사항]
- 첫 렌더링 시 오른쪽 버튼 보이지 않던 문제 해결
- 기본 스크롤바 삭제
=> [홍성욱] list 페이지 스크롤 관련 기능 개선

src/component/common/option/ImageOption.jsx, src/component/pages/Post.jsx
- createRolling 함수에서 필요하지 않은 코드 제거했습니다.
- 사용하지 않는 state를 제거했습니다.
- ImageOption 컴포넌트에서 필요한 부분에 대해서 주석을 적어두었습니다. 해당 주석에 관련된 내용은 월요일에 구현을 시도할 예정입니다.
=> [양서연] post 페이지 코드 정리 및 수정

src/component/common/option/ImageOption.jsx
이미지 url을 넘겨주기 위해 imgbb api를 이용, 이미지를 업로드 후 url을 받아오는 기능을 구현했습니다.
=> [양서연] 이미지 업로드 후 생성된 url 받아오기 기능 구현

src/component/common/option/ImageOption.jsx, src/component/pages/Post.jsx, src/util/api.js
- post 페이지에서 컬러/이미지 버튼 토글시 업로드한 이미지가 사라지는 문제가 있었습니다. 데이터를 불러오는 로직을 post.jsx로 옮겨 이제 버튼 토글 후에도 업로드한 이미지가 사라지지 않습니다. (새로고침 후에는 초기화가 됩니다!)
- 이미지의 post 요청을 하는 api 함수를 api.js 파일로 이동하였습니다.
=> [양서연] ImageOption 데이터 초기화 문제 해결 및 api 함수 이동

src/component/common/option/ColorOption.module.css, src/component/common/option/ImageOption.jsx, src/component/common/option/ImageOption.module.css, src/component/pages/Post.jsx, src/component/pages/Post.module.css
option 컴포넌트와 post 페이지에서 반응형 디자인을 약간 수정해두었습니다.
=> [양서연] option 컴포넌트와 post 페이지 css 변경

src/component/common/header/HeaderService.jsx, src/component/common/header/KaKaoShare.jsx
1. 카카오 이미지 기본 배경일 경우의 url을 추가
2. api key 변경
=> [김수환] kakao공유 수정

package-lock.json, package.json, src/component/common/card/Card.jsx, src/component/common/card/Card.module.css, src/component/common/card/cardCommonTexts.js, src/component/common/cardList/CardList.module.css, src/component/common/header/Header.jsx, src/component/common/header/Header.module.css, src/component/common/header/HeaderService.jsx, src/component/common/header/HeaderService.module.css, src/component/common/header/KaKaoShare.jsx, src/component/common/header/ProfileImages.jsx, src/component/common/header/ProfileImages.module.css, src/component/common/header/headerCommonTexts.js, src/component/pages/Layout.jsx, src/component/pages/PostDetail.jsx, src/component/test/Kim.jsx, src/component/test/Kim.module.css
1. UI 컴포넌트에 있는 데이터 관련 코드들 모두 페이지 컴포넌트로 이동
2. 불필요한 코드 제거 및 css 변경
3. react-spinner 적용하여 코드 변경
=> [김수환] 코드 전반적인 리팩토링

src/component/pages/NotFound.jsx, src/component/pages/NotFound.module.css
=> [김수환] notFound 페이지 변경

src/component/common/option/ProfileImgSelectList.jsx, src/component/common/option/UserProfileOption.jsx, src/component/pages/PostMessage.jsx
- PostMessage 페이지 이미지 로딩 잘 나오게 수정 및 코드 리팩토링
- PostMessage 페이지 버튼 height = tall 로 수정
=> [최원석] PostMessage 페이지 이미지 로딩 잘 나오게 수정

src/component/common/button/Button.jsx, src/component/common/button/Button.module.css, src/component/common/button/ToggleButton.jsx, src/component/common/button/ToggleButton.module.css, src/component/common/cardList/CardList.jsx
- 토글 버튼의 정보를 상위에서 받아 올 수 있도록 변경
- button 태블릿, 모바일 사이즈에서 position 제거
- 삭제하기 버튼 hover, active, focus시 색상 변경
- CardList 부분에서 리액션 갯수가 0일 경우 렌더링 시 숫자 0이 보여서 불리언으로 변경
=> [윤아영] 버튼 컴포넌트 수정

src/component/common/cardList/CardList.module.css
=> [김수환] background-color 제거

src/component/common/option/ImageOption.jsx, src/component/pages/Post.jsx
- 이미지 로드되는 동안 로딩 중이라는 표시인 spinner가 돌 수 있도록 구현했습니다.
- 토글 버튼 코드의 변경에 따라 post 페이지에서 사용 중이던 토글 버튼의 코드를 수정했습니다.
- 길어진 코드에 대해서 보기 편하도록 구조를 조금 정리했습니다.
=> [양서연] ImageOption 컴포넌트 로딩 처리

src/component/pages/NotFound.jsx, src/component/pages/NotFound.module.css
- NotFound 페이지의 디자인을 변경하고 롤링페이퍼 메인페이지로 이동할 수 있도록 버튼을 추가했습니다.
=> [양서연] NotFound 페이지 디자인 변경

src/component/common/option/ProfileImgSelectList.jsx, src/index.css
- 이미지 선택했을때 투명해지게 변경
- 영어일때 글자 깨지는 현상 해결
=> [최원석] ProfileImg 선택했을때 투명해지게 변경, 영어일때 글자 깨지는 현상 해결
